-- LABLAB MOTORSHOP - Supabase/PostgreSQL schema
-- Run this whole file once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.branches (
  branch_id bigint generated by default as identity primary key,
  branch_name text not null unique,
  address text,
  contact_no text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.part_categories (
  category_id bigint generated by default as identity primary key,
  category_name text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.suppliers (
  supplier_id bigint generated by default as identity primary key,
  supplier_name text not null,
  contact_person text,
  phone text,
  email text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.parts (
  part_id bigint generated by default as identity primary key,
  part_name text not null,
  part_number text,
  description text,
  category_id bigint references public.part_categories(category_id) on delete set null,
  unit_price numeric(12,2) not null default 0 check(unit_price>=0),
  reorder_quantity integer not null default 10 check(reorder_quantity>=0),
  reorder_level integer not null default 5 check(reorder_level>=0),
  supplier_id bigint references public.suppliers(supplier_id) on delete set null,
  is_available boolean not null default true,
  image_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  email text,
  first_name text not null default '',
  last_name text not null default '',
  role text not null default 'customer' check(role in ('admin','staff','customer')),
  branch_id bigint references public.branches(branch_id) on delete set null,
  phone text,
  address text,
  profile_image text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.customers (
  customer_id bigint generated by default as identity primary key,
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  first_name text not null default '', last_name text not null default '', email text, phone text, address text,
  is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.stock_levels (
  stock_level_id bigint generated by default as identity primary key,
  part_id bigint not null references public.parts(part_id) on delete cascade,
  branch_id bigint not null references public.branches(branch_id) on delete cascade,
  quantity_on_hand integer not null default 0 check(quantity_on_hand>=0),
  quantity_reserved integer not null default 0 check(quantity_reserved>=0),
  updated_at timestamptz not null default now(), unique(part_id,branch_id)
);
create table if not exists public.stock_history (
  stock_history_id bigint generated by default as identity primary key,
  part_id bigint not null references public.parts(part_id), branch_id bigint not null references public.branches(branch_id),
  transaction_type text not null check(transaction_type in ('ADD','DEDUCT')), quantity_change integer not null,
  reference_id bigint, reference_type text, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now()
);
create table if not exists public.booking (
  booking_id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(customer_id), branch_id bigint not null references public.branches(branch_id),
  booking_date timestamptz not null default now(), reserved_until timestamptz, status text not null default 'pending' check(status in ('pending','confirmed','cancelled','completed')),
  total_amount numeric(12,2) not null default 0, notes text, created_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.booking_items (
  booking_item_id bigint generated by default as identity primary key, booking_id bigint not null references public.booking(booking_id) on delete cascade,
  part_id bigint not null references public.parts(part_id), quantity integer not null check(quantity>0), unit_price numeric(12,2) not null, subtotal numeric(12,2) not null
);
create table if not exists public.transactions (
  transaction_id bigint generated by default as identity primary key, customer_id bigint references public.customers(customer_id), booking_id bigint references public.booking(booking_id),
  branch_id bigint not null references public.branches(branch_id), transaction_date timestamptz not null default now(), transaction_type text not null check(transaction_type in ('DIRECT_SALE','BOOKING_SALE')),
  total_amount numeric(12,2) not null, payment_method text not null check(payment_method in ('CASH','CREDIT_CARD','GCASH','BANK_TRANSFER')),
  payment_status text not null default 'pending' check(payment_status in ('pending','paid','refunded')), notes text, processed_by uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.transaction_items (
  transaction_item_id bigint generated by default as identity primary key, transaction_id bigint not null references public.transactions(transaction_id) on delete cascade,
  part_id bigint not null references public.parts(part_id), quantity integer not null check(quantity>0), unit_price numeric(12,2) not null, subtotal numeric(12,2) not null
);

insert into public.branches(branch_name,address,contact_no) values
('Kidapawan Branch','Kidapawan City, Cotabato','0900-000-0001'),('Magpet Branch','Magpet, Cotabato','0900-000-0002'),('Manongol Branch','Manongol, Cotabato','0900-000-0003') on conflict(branch_name) do nothing;
insert into public.part_categories(category_name) values ('Brake'),('Battery'),('Engine Oil'),('Bearing'),('Bolt & Nut'),('Horn'),('Hand Grip'),('Handle Bar'),('Seat Cover'),('Signal Light'),('Tail Light'),('Tire'),('Interior'),('Spoke'),('Rim'),('Exhaust'),('Elbow'),('Shock'),('Telescopic'),('Sprocket'),('Chain'),('Bulb'),('Switch'),('Sparkplug'),('Carburator') on conflict do nothing;
insert into public.suppliers(supplier_name,contact_person,phone,email) values ('Motoworld Parts Supply','Juan Dela Cruz','0917-000-1111','sales@motoworld.ph'),('AutoMoto Trading','Maria Santos','0917-000-2222','contact@automoto.ph') on conflict do nothing;
insert into public.parts(part_name,part_number,description,category_id,unit_price,reorder_quantity,reorder_level,supplier_id)
select v.n,v.p,v.d,c.category_id,v.price,v.rq,v.rl,s.supplier_id from (values
('Motorcycle Chain 428H','CH-428H','Standard 428H drive chain, 106 links','Chain',650,20,5,'Motoworld Parts Supply'),('Brake Pad Set (Front)','BP-FR-01','Front disc brake pad set','Brake',280,30,8,'Motoworld Parts Supply'),('Spark Plug NGK CPR8EA9','SP-NGK-01','Standard spark plug','Sparkplug',150,40,10,'AutoMoto Trading'),('Engine Oil 1L (SAE 20W-40)','OIL-20W40','Semi-synthetic motorcycle engine oil','Engine Oil',220,50,15,'AutoMoto Trading'),('Motorcycle Battery YTZ7S','BAT-YTZ7S','Sealed maintenance-free battery','Battery',1850,10,3,'Motoworld Parts Supply')) v(n,p,d,cat,price,rq,rl,supp) join public.part_categories c on c.category_name=v.cat join public.suppliers s on s.supplier_name=v.supp where not exists(select 1 from public.parts p where p.part_number=v.p);
insert into public.stock_levels(part_id,branch_id,quantity_on_hand) select p.part_id,b.branch_id,x.qty from (values ('CH-428H','Kidapawan Branch',25),('CH-428H','Magpet Branch',10),('CH-428H','Manongol Branch',4),('BP-FR-01','Kidapawan Branch',40),('BP-FR-01','Magpet Branch',15),('BP-FR-01','Manongol Branch',6),('SP-NGK-01','Kidapawan Branch',60),('SP-NGK-01','Magpet Branch',20),('SP-NGK-01','Manongol Branch',8),('OIL-20W40','Kidapawan Branch',70),('OIL-20W40','Magpet Branch',25),('OIL-20W40','Manongol Branch',12),('BAT-YTZ7S','Kidapawan Branch',12),('BAT-YTZ7S','Magpet Branch',4),('BAT-YTZ7S','Manongol Branch',2)) x(part_number,branch_name,qty) join public.parts p on p.part_number=x.part_number join public.branches b on b.branch_name=x.branch_name on conflict(part_id,branch_id) do nothing;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,username,email,first_name,last_name) values(new.id,coalesce(new.raw_user_meta_data->>'username',split_part(new.email,'@',1)),new.email,coalesce(new.raw_user_meta_data->>'first_name',''),coalesce(new.raw_user_meta_data->>'last_name','')) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Helper functions prevent infinite-recursion when RLS policies need to check a user's role.
create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create or replace function public.is_staff_or_admin() returns boolean
language sql stable security definer set search_path = public
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role in ('admin','staff')); $$;

alter table public.profiles enable row level security; alter table public.branches enable row level security; alter table public.parts enable row level security; alter table public.part_categories enable row level security; alter table public.suppliers enable row level security; alter table public.stock_levels enable row level security; alter table public.stock_history enable row level security; alter table public.customers enable row level security; alter table public.booking enable row level security; alter table public.booking_items enable row level security; alter table public.transactions enable row level security; alter table public.transaction_items enable row level security;

drop policy if exists profiles_self_or_admin on public.profiles; create policy profiles_self_or_admin on public.profiles for select using (auth.uid()=id or public.is_admin());
drop policy if exists profiles_update_admin_or_self on public.profiles; create policy profiles_update_admin_or_self on public.profiles for update using (auth.uid()=id or public.is_admin()) with check (auth.uid()=id or public.is_admin());
drop policy if exists public_read_branches on public.branches; create policy public_read_branches on public.branches for select using (true); drop policy if exists admin_write_branches on public.branches; create policy admin_write_branches on public.branches for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists public_read_categories on public.part_categories; create policy public_read_categories on public.part_categories for select using (true); drop policy if exists admin_write_categories on public.part_categories; create policy admin_write_categories on public.part_categories for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists public_read_parts on public.parts; create policy public_read_parts on public.parts for select using (true); drop policy if exists admin_write_parts on public.parts; create policy admin_write_parts on public.parts for all using (public.is_staff_or_admin()) with check (public.is_staff_or_admin());
drop policy if exists staff_read_stock on public.stock_levels; create policy staff_read_stock on public.stock_levels for select using (true); drop policy if exists admin_write_stock on public.stock_levels; create policy admin_write_stock on public.stock_levels for all using (public.is_staff_or_admin()) with check (public.is_staff_or_admin());
drop policy if exists customers_self_or_admin on public.customers; create policy customers_self_or_admin on public.customers for select using (user_id=auth.uid() or public.is_staff_or_admin()); create policy customers_insert_self on public.customers for insert with check(user_id=auth.uid());
drop policy if exists bookings_customer_or_admin on public.booking; create policy bookings_customer_or_admin on public.booking for select using (exists(select 1 from public.customers c where c.customer_id=booking.customer_id and c.user_id=auth.uid()) or public.is_staff_or_admin()); drop policy if exists bookings_customer_insert on public.booking; create policy bookings_customer_insert on public.booking for insert with check(exists(select 1 from public.customers c where c.customer_id=booking.customer_id and c.user_id=auth.uid())); drop policy if exists bookings_admin_update on public.booking; create policy bookings_admin_update on public.booking for update using(public.is_staff_or_admin());
create policy booking_items_customer_or_admin on public.booking_items for select using(exists(select 1 from public.booking b join public.customers c on c.customer_id=b.customer_id where b.booking_id=booking_items.booking_id and c.user_id=auth.uid()) or public.is_staff_or_admin());
drop policy if exists transactions_admin_read on public.transactions; create policy transactions_admin_read on public.transactions for select using(public.is_staff_or_admin());
drop policy if exists transaction_items_admin_read on public.transaction_items; create policy transaction_items_admin_read on public.transaction_items for select using(public.is_staff_or_admin());

insert into storage.buckets(id,name,public) values ('part-images','part-images',true) on conflict(id) do nothing;
drop policy if exists part_images_public_read on storage.objects; create policy part_images_public_read on storage.objects for select using(bucket_id='part-images');
drop policy if exists part_images_admin_upload on storage.objects; create policy part_images_admin_upload on storage.objects for insert with check(bucket_id='part-images' and public.is_staff_or_admin());

-- After creating admin@lablab.com in Authentication, run:
-- update public.profiles set role='admin', username='admin' where email='admin@lablab.com';
